/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.dadosp;

import javax.swing.Icon;
import javax.swing.JOptionPane;

/**
 *
 * @author 37178
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+ "\\src\\main\\java\\com\\mycompany\\dadosp\\imagen\\dado1.png"));

        jLabel1.setIcon(new javax.swing.ImageIcon(System.getProperty("user.dir")+ "\\src\\main\\java\\com\\mycompany\\dadosp\\imagen\\Dado6.png"));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Tirar Dados");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addGap(9, 9, 9)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 77, Short.MAX_VALUE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        StringBuilder resultado = new StringBuilder();
        int tiradas = 36;
        int contador = 0;
        double dosSuma = 0;
        double tresSuma = 0;
        double cuatroSuma = 0;
        double cincoSuma = 0;
        double seisSuma = 0;
        double sieteSuma = 0;
        double ochoSuma = 0;
        double nueveSuma = 0;
        double diezSuma = 0;
        double onceSuma = 0;
        double doceSuma = 0;
        
        double divDos = 0;
        double divTres = 0;
        double divCuatro = 0;
        double divCinco = 0;
        double divSeis = 0;
        double divSiete = 0;
        double divOcho = 0;
        double divNueve = 0;
        double divDiez = 0;
        double divOnce = 0;
        double divDoce = 0;
        
        double media = 0;   
        double CuadradoPi = 0;
        double Varianza = 0;
        double Desviacion = 0;

      
        Icon uno = new javax.swing.ImageIcon(System.getProperty("user.dir")+ "\\src\\main\\java\\com\\mycompany\\dadosp\\imagen\\dado1.png");
        Icon dos = new javax.swing.ImageIcon(System.getProperty("user.dir")+ "\\src\\main\\java\\com\\mycompany\\dadosp\\imagen\\Dado2.png");
        Icon tres = new javax.swing.ImageIcon(System.getProperty("user.dir")+ "\\src\\main\\java\\com\\mycompany\\dadosp\\imagen\\Dado3.png");
        Icon cuatro = new javax.swing.ImageIcon(System.getProperty("user.dir")+ "\\src\\main\\java\\com\\mycompany\\dadosp\\imagen\\Dado4.png");
        Icon cinco = new javax.swing.ImageIcon(System.getProperty("user.dir")+ "\\src\\main\\java\\com\\mycompany\\dadosp\\imagen\\Dado5.png");
        Icon seis = new javax.swing.ImageIcon(System.getProperty("user.dir")+ "\\src\\main\\java\\com\\mycompany\\dadosp\\imagen\\Dado6.png");
        
            while (contador < tiradas) {
                int dado1 = (int)(Math.random()*6)+1;
                int dado2 = (int)(Math.random()*6)+1;
                
                switch(dado1){
            case 1 -> jLabel2.setIcon(uno);
            case 2 -> jLabel2.setIcon(dos);
            case 3 -> jLabel2.setIcon(tres);
            case 4 -> jLabel2.setIcon(cuatro);
            case 5 -> jLabel2.setIcon(cinco);
            case 6 -> jLabel2.setIcon(seis);
        }
        
        switch(dado2){
            case 1 -> jLabel1.setIcon(uno);
            case 2 -> jLabel1.setIcon(dos);
            case 3 -> jLabel1.setIcon(tres);
            case 4 -> jLabel1.setIcon(cuatro);
            case 5 -> jLabel1.setIcon(cinco);
            case 6 -> jLabel1.setIcon(seis);
            
        }
        contador++;

                   
            int resultados = dado1 + dado2;
            
            switch(resultados){
                case 2:
                    dosSuma = dosSuma + 1;
                    break;
                case 3:
                    tresSuma = tresSuma + 1;
                    break;
                case 4:
                    cuatroSuma = cuatroSuma + 1;
                    break;
                case 5:
                    cincoSuma = cincoSuma + 1;
                    break;
                case 6:
                    seisSuma = seisSuma + 1;
                    break;
                case 7:
                    sieteSuma = sieteSuma + 1; 
                    break;
                case 8:
                    ochoSuma = ochoSuma + 1;
                    break;
                case 9:
                    nueveSuma = nueveSuma + 1;
                    break;
                case 10:
                    diezSuma = diezSuma + 1;
                    break;
                case 11:
                    onceSuma = onceSuma + 1;
                    break;
                case 12:
                    doceSuma = doceSuma + 1;
                    break;
             
            }
            
            
            divDos = dosSuma/36;
            divTres = tresSuma/36;
            divCuatro = cuatroSuma/36;
            divCinco = cincoSuma/36;
            divSeis = seisSuma/36;
            divSiete = sieteSuma/36;
            divOcho = ochoSuma/36;
            divNueve = nueveSuma/36;
            divDiez = diezSuma/36;
            divOnce = onceSuma/36;
            divDoce = doceSuma/36;
            
            media = (divDos * 2) + (divTres * 3) + (divCuatro * 4) +(divCinco * 5) + (divSeis * 6) + (divSiete * 7) + (divOcho * 8)
                    + (divNueve * 9) + (divDiez * 10) + (divOnce * 11) + (divDoce * 12);
            
            CuadradoPi = (divDos * 4) + (divTres * 9) + (divCuatro * 16) +(divCinco * 25) + (divSeis * 36) + (divSiete * 49) + (divOcho * 64)
                    + (divNueve * 81) + (divDiez * 100) + (divOnce * 121) + (divDoce * 144);
            
            Varianza = CuadradoPi - (media*media);
            
            Desviacion = Math.sqrt(Varianza);
            
            
            jTextArea1.setText("");
           
            }
            jTextArea1.append("Probrabilidad que las caras sumen 2: "+ String.valueOf((int)dosSuma)+"/36"+"\n");
            
            jTextArea1.append("Probrabilidad que las caras sumen 3: "+ String.valueOf((int)tresSuma)+"/36"+"\n");
            
            jTextArea1.append("Probrabilidad que las caras sumen 4: "+ String.valueOf((int)cuatroSuma)+"/36"+"\n");

            jTextArea1.append("Probrabilidad que las caras sumen 5: "+ String.valueOf((int)cincoSuma)+"/36"+"\n");
            
            jTextArea1.append("Probrabilidad que las caras sumen 6: "+ String.valueOf((int)seisSuma)+"/36"+"\n");
            
            jTextArea1.append("Probrabilidad que las caras sumen 7: "+ String.valueOf((int)sieteSuma)+"/36"+"\n");
            
            jTextArea1.append("Probrabilidad que las caras sumen 8: "+ String.valueOf((int)ochoSuma)+"/36"+"\n");
            
            jTextArea1.append("Probrabilidad que las caras sumen 9: "+ String.valueOf((int)nueveSuma)+"/36"+"\n");
            
            jTextArea1.append("Probrabilidad que las caras sumen 10: "+ String.valueOf((int)diezSuma)+"/36"+"\n");
            
            jTextArea1.append("Probrabilidad que las caras sumen 11: "+ String.valueOf((int)onceSuma)+"/36"+"\n");
            
            jTextArea1.append("Probrabilidad que las caras sumen 12: "+ String.valueOf((int)doceSuma)+"/36"+"\n");
            
            jTextArea1.append("\n");
            
            jTextArea1.append("Media: "+ media + "\n");
            
            jTextArea1.append("Varianza: "+ Varianza + "\n");
            
            jTextArea1.append("Desviacion: "+ Desviacion + "\n");
            
            
       
            /*
            System.out.println(divDos);
            System.out.println(divTres);
            System.out.println(divCuatro);
            System.out.println(divCinco);
            System.out.println(divSeis);
            System.out.println(divSiete);
            System.out.println(divOcho);
            System.out.println(divNueve);
            System.out.println(divDiez);
            System.out.println(divOnce);
            System.out.println(divDoce);
            
            System.out.println(dosSuma);
            System.out.println(tresSuma);
            System.out.println(cuatroSuma);
            System.out.println(cincoSuma);
            System.out.println(seisSuma);
            System.out.println(sieteSuma);
            System.out.println(ochoSuma);
            System.out.println(nueveSuma);
            System.out.println(diezSuma);
            System.out.println(onceSuma);
            System.out.println(doceSuma);
            System.out.println(CuadradoPi);
            */

            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Menú A = new Menú();       
        A.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
